
import { Translations } from './types';

export const TRANSLATIONS: Translations = {
  bn: {
    appName: 'চিরকুট',
    tagline: 'বেনামী বার্তা গ্রহণ করুন এবং আপনার সোশ্যাল মিডিয়ায় শেয়ার করুন।',
    getStarted: 'শুরু করুন',
    login: 'লগইন',
    register: 'রেজিস্টার',
    username: 'ইউজারনেম',
    fullName: 'পুরো নাম',
    password: 'পাসওয়ার্ড',
    usernamePlaceholder: 'আপনার ইউজারনেম (যেমন: robin_01)',
    fullNamePlaceholder: 'আপনার পুরো নাম লিখুন',
    passwordPlaceholder: 'গোপন পাসওয়ার্ডটি দিন',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    yourLink: 'আপনার চিরকুট লিঙ্ক:',
    copyLink: 'লিঙ্ক কপি করুন',
    copied: 'কপি হয়েছে!',
    shareOn: 'শেয়ার করুন:',
    inbox: 'ইনবক্স',
    noMessages: 'এখনো কোনো চিরকুট আসেনি। আপনার লিঙ্কটি শেয়ার করুন!',
    sendMessage: 'একটি গোপন চিরকুট পাঠান',
    send: 'পাঠিয়ে দিন',
    anonymousPlaceholder: 'এখানে আপনার গোপন কথাটি লিখুন...',
    aiSuggest: 'AI দিয়ে সাজেশান নিন',
    logout: 'লগ আউট',
    backToHome: 'হোমে ফিরে যান',
    success: 'সফলভাবে পাঠানো হয়েছে!',
    errorUsernameTaken: 'এই ইউজারনেমটি ইতিমধ্যে নেওয়া হয়েছে।',
    errorAuth: 'ইউজারনেম অথবা পাসওয়ার্ড সঠিক নয়।',
    welcomeBack: 'স্বাগতম!',
    loading: 'অপেক্ষা করুন...',
    settings: 'প্রোফাইল সেটিংস',
    saveChanges: 'পরিবর্তন সেভ করুন',
    shareCard: 'কার্ড হিসেবে শেয়ার',
    download: 'ডাউনলোড',
    close: 'বন্ধ করুন',
  },
  en: {
    appName: 'Chirkut',
    tagline: 'Receive anonymous messages and share them on your social media.',
    getStarted: 'Get Started',
    login: 'Login',
    register: 'Register',
    username: 'Username',
    fullName: 'Full Name',
    password: 'Password',
    usernamePlaceholder: 'Unique username (e.g. robin_01)',
    fullNamePlaceholder: 'Your full name',
    passwordPlaceholder: 'Choose a password',
    createAccount: 'Create Account',
    yourLink: 'Your Chirkut Link:',
    copyLink: 'Copy Link',
    copied: 'Copied!',
    shareOn: 'Share on:',
    inbox: 'Inbox',
    noMessages: 'No messages yet. Share your link!',
    sendMessage: 'Send a secret message',
    send: 'Send Now',
    anonymousPlaceholder: 'Write your secret message here...',
    aiSuggest: 'Get AI Suggestion',
    logout: 'Logout',
    backToHome: 'Back to Home',
    success: 'Sent successfully!',
    errorUsernameTaken: 'This username is already taken.',
    errorAuth: 'Invalid username or password.',
    welcomeBack: 'Welcome Back!',
    loading: 'Loading...',
    settings: 'Profile Settings',
    saveChanges: 'Save Changes',
    shareCard: 'Share as Card',
    download: 'Download',
    close: 'Close',
  }
};
